### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by Embrace-Arch** [VITA-Group/VLM-3R#23]
I have an A100 graphic card, and when I run the following command:  CUDA_VISIBLE_DEVICES=0 bash scripts/video/demo/video_demo.sh  ./vlm-3r-llava-qwen2-lora     qwen_1_5 32 2 average grid True   playground/demo/47334096.mp4   ./LLaVA-NeXT-Video-7B-Qwen2 or bash scripts/image/demo/image_demo.sh ./vlm-3r-llava-qwen2-lora  qwen_1_5 2 average grid True  playground/demo/scene_47334096_imgs  ./LLaVA-NeXT-Video-7B-Qwen2  there will be some error as following:
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/opt/conda/conda-bld/pytorch_1699449201336/work/aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

I encounter an error. Could you help me figure out what's going wrong? I configured the conda virtual environment according to your method

**Comment by gyj155** [comment]
Hi, 
I encountered same issues on an A6000 GPU and I have found a way to solve this. 
I first encountered `CUDA error: CUBLAS_STATUS_EXECUTION_FAILED` and index assertion failures.

The cause was that spatial tower was only assigned a dtype but never moved to CUDA device, causing mixed CPU/GPU operations.

**File**: `llava/model/language_model/llava_qwen.py`
**Change** (line 69):
```python
model.get_spatial_tower().to(device="cuda", dtype=kwargs.get("torch_dtype", torch.float16))
```

The second issue was that RoPE2D cannot handle negative position indices
`srcIndex < srcSelectDimSize  failed. /pytorch/aten/src/ATen/native/cuda/Indexing.cu:1553: indexSelectLargeIndex: block: [0,0,0], thread: [23,0,0] Assertion srcIndex < srcSelectDimSize failed. …
RuntimeError: CUDA error: device-side assert triggered in pos_embed.py:172.`

The cause was that pose tokens use `-1` as position markers. When RoPE2D calls, `int(positions.max()) + 1` - fails if all positions are negative, `torch.nn.functional.embedding(pos1d, cos)` embedding doesn't accept negative indices

**File**: `CUT3R/src/croco/models/pos_embed.py`
**Change** (line 172):
```python
# Handle negative positions by using max of non-negative values
max_pos = positions[positions >= 0].max() if (positions >= 0).any() else torch.tensor(0, device=positions.device)
cos, sin = self.get_cos_sin(
    D, int(max_pos) + 1, tokens.device, tokens.dtype
)
```

**File**: `CUT3R/src/croco/models/pos_embed.py`
**Change** (line 155):
```python
def apply_rope1d(self, tokens, pos1d, cos, sin):
    assert pos1d.ndim == 2
    # Clamp negative positions to 0 for embedding lookup (pose tokens use -1)
    pos1d_clamped = torch.clamp(pos1d, min=0)
    cos = torch.nn.functional.embedding(pos1d_clamped, cos)[:, None, :, :]
    sin = torch.nn.functional.embedding(pos1d_clamped, sin)[:, None, :, :]
    return (tokens * cos) + (self.rotate_half(tokens) * sin)
```
